#+SETUPFILE: Setup/setupFile.org
#+TITLE: Emacs code 

* What is it?

This package is a tool to quickly generate a project structure to be
used with OrgMode. We provide a bash script =createOrgProject.sh
PROJECTNAME= that populate the =PROJECTNAME/= directory with all the
required files.


The generated =PROJECTNAME/= directory structure is:
#+BEGIN_EXAMPLE
TODO
#+END_EXAMPLE


To use the project (template) simply add this function to your Emacs =init.el= 

#+NAME: my-project-configuration
#+BEGIN_SRC emacs-lisp 
(defun my-project-configuration ()
  "Find my-project-root as parent directory of the closest .dir-locals.el file, 
then load my-project-root/Setup/setupFile.el project configuration file "
  (interactive)
  (let ((enable-local-variables :all))
    (setq my-project-root (let ((d (dir-locals-find-file ".")))
			    (when d (file-name-directory (if (stringp d) d (car d))))))

    (if my-project-root
	(let ((my-project-setup-file (concat my-project-root "Setup/setupFile.el")))
	  (if (file-exists-p my-project-setup-file)
	      (load my-project-setup-file nil t t nil)
	    (error "Project %s setup file not found" my-project-setup-file)))
      (error "Project root dir not found (missing .dir-locals.el file)"))))
#+END_SRC

Its role is to found project root (the closest .dir-locals.el file)
and to load the project configuration =Setup/setupFile.el=. 

* The script

#+BEGIN_SRC bash :tangle create_orgMode_project :shebang #!/bin/bash
set -e

force=0
projectname=""

#if [ ("$1" == "")||("$#" -ge 2) ]; then
if [ "$1" == "" ]; then
    echo "Usage: $(basename $0) projectname -f"
    echo "> create a directory ./projectname/ and populate it"
    echo "> use -f to force overwriting"
    exit 0
fi

while [ "$1" != "" ]; do
    case $1 in
        -f )       force=1
                   ;;
        * )        projectname=$1
    esac
    shift
done

echo "force $force project $projectname"

echo
#+END_SRC
* Quick starter

#+BEGIN_SRC 
createOrgProject.sh MyProject
#+END_SRC

#+BEGIN_SRC 
emacs  MyProject/theindex.org &
#+END_SRC
(attention do not forget to define the [[my-project-configuration][my-project-configuration]] function)

Then you can Publish it: 
 - M-x my-project-configuration
 - C-c C-e P p
-> then firefox theindex.html

Add a note or a bibliographical item.
